# Generated by Django 4.1.3 on 2025-06-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='facility_code',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='identifier_number',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='patient_name',
        ),
    ]
