# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_role_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('paused', 'Tạm dừng'), ('holiday', 'Nghỉ lễ'), ('maintenance', 'Bảo trì'), ('closed', 'Ngừng hoạt động')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='api.service'),
        ),
    ]
