# Generated by Django 6.0.3 on 2026-03-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service_medicalfacility_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('kham_benh', 'Khám bệnh'), ('xet_nghiem', 'Xét nghiệm'), ('chan_doan_hinh_anh', 'Chẩn đoán hình ảnh'), ('phau_thuat', 'Phẫu thuật'), ('noi_khoa', 'Nội khoa'), ('ngoai_khoa', 'Ngoại khoa'), ('san_phu_khoa', 'Sản phụ khoa'), ('nhi_khoa', 'Nhi khoa'), ('rang_ham_mat', 'Răng hàm mặt'), ('mat', 'Mắt'), ('tai_mui_hong', 'Tai mũi họng'), ('phuc_hoi_chuc_nang', 'Phục hồi chức năng'), ('khac', 'Khác')], default='khac', max_length=50),
        ),
    ]
