# Generated by Django 6.0.3 on 2026-03-13 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thực hiện'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_examination_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_services', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='examination_service_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('examination_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.examinationservice')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Chờ khám'), ('in_progress', 'Đang khám'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('overall_result', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.medicalfacility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='examinationservice',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_services', to='api.medicalexamination'),
        ),
        migrations.CreateModel(
            name='ExaminationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='examination_documents/')),
                ('document_type', models.CharField(choices=[('attachment', 'File đính kèm'), ('result', 'File kết quả')], default='attachment', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.medicalexamination')),
            ],
        ),
    ]
