# Generated by Django 6.0.3 on 2026-03-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_examination_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationservice',
            name='service_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
