# Generated by Django 6.0.3 on 2026-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationservice',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
