# Generated by Django 6.0.3 on 2026-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_price_to_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Chờ thanh toán'), ('pending', 'Chờ khám'), ('in_progress', 'Đang khám'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='awaiting_payment', max_length=20),
        ),
    ]
