# Generated by Django 4.1.3 on 2026-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_update_examination_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationservice',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identifier_type',
            field=models.CharField(choices=[('insurance', 'Số BHYT'), ('national_id', 'CMND/CCCD'), ('phone', 'Số điện thoại')], max_length=20),
        ),
    ]
