# Generated by Django 4.1.3 on 2026-03-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_examinationservice_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_consults', to=settings.AUTH_USER_MODEL)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consults', to='api.medicalexamination')),
            ],
            options={
                'unique_together': {('examination', 'doctor')},
            },
        ),
    ]
