# Generated by Django 4.1.3 on 2026-03-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_examinationconsult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.patient'),
        ),
    ]
